
-- 统计预测时间前一周的用户与商品的交互信息
-- 由于商品并不是每天都有记录信息，先取平均，在乘以7，大概估计7天的总交互信息
-- 考虑准确性，保持两位小数
-- 生成表格 TC_UI_FEATURE

CREATE TABLE TC_TEMP AS
SELECT
  ITEM_ID,
  COUNT(*) AS RECORDS,
  SUM(PV_IPV) AS PV_IPV,
  SUM(PV_UV) AS PV_UV ,
  SUM(CART_IPV) AS CART_IPV,
  SUM(CART_UV) AS CART_UV,
  SUM(COLLECT_UV) AS COLLECT_UV,
  SUM(NUM_GMV) AS NUM_GMV,
  SUM(AMT_GMV) AS AMT_GMV,
  SUM(QTY_GMV) AS QTY_GMV,
  SUM(UNUM_GMV) AS UNUM_GMV,
  SUM(AMT_ALIPAY) AS AMT_ALIPAY,
  SUM(NUM_APLIPAY) AS NUM_APLIPAY,
  SUM(QTY_APIPAY) AS QTY_APIPAY,
  SUM(UNUM_ALIPAY) AS UNUM_ALIPAY,
  SUM(ZTC_PV_IPV) AS ZTC_PV_IPV,
  SUM(TBK_PV_IPV) AS TBK_PV_IPV,
  SUM(SS_PV_IPV) AS SS_PV_IPV,
  SUM(JHS_PV_IPV) AS JHS_PV_IPV ,
  SUM(ZTC_PV_UV) AS ZTC_PV_UV,
  SUM(TBK_PV_UV) AS TBK_PV_UV,
  SUM(SS_PV_UV) AS SS_PV_UV,
  SUM(JHS_PV_UV) AS JHS_PV_UV,
  SUM(NUM_AIPAY_HJHS) AS NUM_AIPAY_HJHS,
  SUM(AMT_APLIPAY_NJHS) AS AMT_APLIPAY_NJHS,
  SUM(QTY_ALIPAY_NJHS) AS QTY_ALIPAY_NJHS,
  SUM(UNUM_ALIPAY_NJHS) AS UNUM_ALIPAY_NJHS
FROM TC_CN_TRAIN_20141121_0304 
WHERE TIME >='20150212' AND TIME <='20150218'
GROUP BY ITEM_ID;

DROP TABLE TC_UI_FEATURE_TRAIN;
CREATE TABLE TC_UI_FEATURE_TRAIN AS
SELECT 
  ITEM_ID,
  ROUND(PV_IPV*7/RECORDS,2) AS PV_IPV,
  ROUND(PV_UV*7/RECORDS,2) AS PV_UV ,
  ROUND(CART_IPV*7/RECORDS,2) AS CART_IPV,
  ROUND(CART_UV*7/RECORDS,2) AS CART_UV,
  ROUND(COLLECT_UV*7/RECORDS,2) AS COLLECT_UV,
  ROUND(NUM_GMV*7/RECORDS,2) AS NUM_GMV,
  ROUND(AMT_GMV*7/RECORDS,2) AS AMT_GMV,
  ROUND(QTY_GMV*7/RECORDS,2) AS QTY_GMV,
  ROUND(UNUM_GMV*7/RECORDS,2) AS UNUM_GMV,
  ROUND(AMT_ALIPAY*7/RECORDS,2) AS AMT_ALIPAY,
  ROUND(NUM_APLIPAY*7/RECORDS,2) AS NUM_APLIPAY,
  ROUND(QTY_APIPAY*7/RECORDS,2) AS QTY_APIPAY,
  ROUND(UNUM_ALIPAY*7/RECORDS,2) AS UNUM_ALIPAY,
  ROUND(ZTC_PV_IPV*7/RECORDS,2) AS ZTC_PV_IPV,
  ROUND(TBK_PV_IPV*7/RECORDS,2) AS TBK_PV_IPV,
  ROUND(SS_PV_IPV*7/RECORDS,2) AS SS_PV_IPV,
  ROUND(JHS_PV_IPV*7/RECORDS,2) AS JHS_PV_IPV ,
  ROUND(ZTC_PV_UV*7/RECORDS,2) AS ZTC_PV_UV,
  ROUND(TBK_PV_UV*7/RECORDS,2) AS TBK_PV_UV,
  ROUND(SS_PV_UV*7/RECORDS,2) AS SS_PV_UV,
  ROUND(JHS_PV_UV*7/RECORDS,2) AS JHS_PV_UV,
  ROUND(NUM_AIPAY_HJHS*7/RECORDS,2) AS NUM_AIPAY_HJHS,
  ROUND(AMT_APLIPAY_NJHS*7/RECORDS,2) AS AMT_APLIPAY_NJHS,
  ROUND(QTY_ALIPAY_NJHS*7/RECORDS,2) AS QTY_ALIPAY_NJHS,
  ROUND(UNUM_ALIPAY_NJHS*7/RECORDS,2) AS UNUM_ALIPAY_NJHS
FROM TC_TEMP;


-- ------------------------------
-- FOR TESTING
DROP TABLE TC_TEMP;
CREATE TABLE TC_TEMP AS
SELECT
  ITEM_ID,
  COUNT(*) AS RECORDS,
  SUM(PV_IPV) AS PV_IPV,
  SUM(PV_UV) AS PV_UV ,
  SUM(CART_IPV) AS CART_IPV,
  SUM(CART_UV) AS CART_UV,
  SUM(COLLECT_UV) AS COLLECT_UV,
  SUM(NUM_GMV) AS NUM_GMV,
  SUM(AMT_GMV) AS AMT_GMV,
  SUM(QTY_GMV) AS QTY_GMV,
  SUM(UNUM_GMV) AS UNUM_GMV,
  SUM(AMT_ALIPAY) AS AMT_ALIPAY,
  SUM(NUM_APLIPAY) AS NUM_APLIPAY,
  SUM(QTY_APIPAY) AS QTY_APIPAY,
  SUM(UNUM_ALIPAY) AS UNUM_ALIPAY,
  SUM(ZTC_PV_IPV) AS ZTC_PV_IPV,
  SUM(TBK_PV_IPV) AS TBK_PV_IPV,
  SUM(SS_PV_IPV) AS SS_PV_IPV,
  SUM(JHS_PV_IPV) AS JHS_PV_IPV ,
  SUM(ZTC_PV_UV) AS ZTC_PV_UV,
  SUM(TBK_PV_UV) AS TBK_PV_UV,
  SUM(SS_PV_UV) AS SS_PV_UV,
  SUM(JHS_PV_UV) AS JHS_PV_UV,
  SUM(NUM_AIPAY_HJHS) AS NUM_AIPAY_HJHS,
  SUM(AMT_APLIPAY_NJHS) AS AMT_APLIPAY_NJHS,
  SUM(QTY_ALIPAY_NJHS) AS QTY_ALIPAY_NJHS,
  SUM(UNUM_ALIPAY_NJHS) AS UNUM_ALIPAY_NJHS
FROM TC_CN_TEST_20150305_0616 
WHERE TIME >='20150527' AND TIME <='20150602'
GROUP BY ITEM_ID;

DROP TABLE TC_UI_FEATURE_TEST;
CREATE TABLE TC_UI_FEATURE_TEST AS
SELECT 
  ITEM_ID,
  ROUND(PV_IPV*7/RECORDS,2) AS PV_IPV,
  ROUND(PV_UV*7/RECORDS,2) AS PV_UV ,
  ROUND(CART_IPV*7/RECORDS,2) AS CART_IPV,
  ROUND(CART_UV*7/RECORDS,2) AS CART_UV,
  ROUND(COLLECT_UV*7/RECORDS,2) AS COLLECT_UV,
  ROUND(NUM_GMV*7/RECORDS,2) AS NUM_GMV,
  ROUND(AMT_GMV*7/RECORDS,2) AS AMT_GMV,
  ROUND(QTY_GMV*7/RECORDS,2) AS QTY_GMV,
  ROUND(UNUM_GMV*7/RECORDS,2) AS UNUM_GMV,
  ROUND(AMT_ALIPAY*7/RECORDS,2) AS AMT_ALIPAY,
  ROUND(NUM_APLIPAY*7/RECORDS,2) AS NUM_APLIPAY,
  ROUND(QTY_APIPAY*7/RECORDS,2) AS QTY_APIPAY,
  ROUND(UNUM_ALIPAY*7/RECORDS,2) AS UNUM_ALIPAY,
  ROUND(ZTC_PV_IPV*7/RECORDS,2) AS ZTC_PV_IPV,
  ROUND(TBK_PV_IPV*7/RECORDS,2) AS TBK_PV_IPV,
  ROUND(SS_PV_IPV*7/RECORDS,2) AS SS_PV_IPV,
  ROUND(JHS_PV_IPV*7/RECORDS,2) AS JHS_PV_IPV ,
  ROUND(ZTC_PV_UV*7/RECORDS,2) AS ZTC_PV_UV,
  ROUND(TBK_PV_UV*7/RECORDS,2) AS TBK_PV_UV,
  ROUND(SS_PV_UV*7/RECORDS,2) AS SS_PV_UV,
  ROUND(JHS_PV_UV*7/RECORDS,2) AS JHS_PV_UV,
  ROUND(NUM_AIPAY_HJHS*7/RECORDS,2) AS NUM_AIPAY_HJHS,
  ROUND(AMT_APLIPAY_NJHS*7/RECORDS,2) AS AMT_APLIPAY_NJHS,
  ROUND(QTY_ALIPAY_NJHS*7/RECORDS,2) AS QTY_ALIPAY_NJHS,
  ROUND(UNUM_ALIPAY_NJHS*7/RECORDS,2) AS UNUM_ALIPAY_NJHS
FROM TC_TEMP;


-- -------------------------------------------------------------------------------------
-- FOR EVALUATING
DROP TABLE TC_TEMP;
CREATE TABLE TC_TEMP AS
SELECT
  ITEM_ID,
  COUNT(*) AS RECORDS,
  SUM(PV_IPV) AS PV_IPV,
  SUM(PV_UV) AS PV_UV ,
  SUM(CART_IPV) AS CART_IPV,
  SUM(CART_UV) AS CART_UV,
  SUM(COLLECT_UV) AS COLLECT_UV,
  SUM(NUM_GMV) AS NUM_GMV,
  SUM(AMT_GMV) AS AMT_GMV,
  SUM(QTY_GMV) AS QTY_GMV,
  SUM(UNUM_GMV) AS UNUM_GMV,
  SUM(AMT_ALIPAY) AS AMT_ALIPAY,
  SUM(NUM_APLIPAY) AS NUM_APLIPAY,
  SUM(QTY_APIPAY) AS QTY_APIPAY,
  SUM(UNUM_ALIPAY) AS UNUM_ALIPAY,
  SUM(ZTC_PV_IPV) AS ZTC_PV_IPV,
  SUM(TBK_PV_IPV) AS TBK_PV_IPV,
  SUM(SS_PV_IPV) AS SS_PV_IPV,
  SUM(JHS_PV_IPV) AS JHS_PV_IPV ,
  SUM(ZTC_PV_UV) AS ZTC_PV_UV,
  SUM(TBK_PV_UV) AS TBK_PV_UV,
  SUM(SS_PV_UV) AS SS_PV_UV,
  SUM(JHS_PV_UV) AS JHS_PV_UV,
  SUM(NUM_AIPAY_HJHS) AS NUM_AIPAY_HJHS,
  SUM(AMT_APLIPAY_NJHS) AS AMT_APLIPAY_NJHS,
  SUM(QTY_ALIPAY_NJHS) AS QTY_ALIPAY_NJHS,
  SUM(UNUM_ALIPAY_NJHS) AS UNUM_ALIPAY_NJHS
FROM TC_CN_EVAL_20150617_0928
WHERE TIME >='20150908' AND TIME <='20150914'
GROUP BY ITEM_ID;

DROP TABLE TC_UI_FEATURE_EVAL;
CREATE TABLE TC_UI_FEATURE_EVAL AS
SELECT 
  ITEM_ID,
  ROUND(PV_IPV*7/RECORDS,2) AS PV_IPV,
  ROUND(PV_UV*7/RECORDS,2) AS PV_UV ,
  ROUND(CART_IPV*7/RECORDS,2) AS CART_IPV,
  ROUND(CART_UV*7/RECORDS,2) AS CART_UV,
  ROUND(COLLECT_UV*7/RECORDS,2) AS COLLECT_UV,
  ROUND(NUM_GMV*7/RECORDS,2) AS NUM_GMV,
  ROUND(AMT_GMV*7/RECORDS,2) AS AMT_GMV,
  ROUND(QTY_GMV*7/RECORDS,2) AS QTY_GMV,
  ROUND(UNUM_GMV*7/RECORDS,2) AS UNUM_GMV,
  ROUND(AMT_ALIPAY*7/RECORDS,2) AS AMT_ALIPAY,
  ROUND(NUM_APLIPAY*7/RECORDS,2) AS NUM_APLIPAY,
  ROUND(QTY_APIPAY*7/RECORDS,2) AS QTY_APIPAY,
  ROUND(UNUM_ALIPAY*7/RECORDS,2) AS UNUM_ALIPAY,
  ROUND(ZTC_PV_IPV*7/RECORDS,2) AS ZTC_PV_IPV,
  ROUND(TBK_PV_IPV*7/RECORDS,2) AS TBK_PV_IPV,
  ROUND(SS_PV_IPV*7/RECORDS,2) AS SS_PV_IPV,
  ROUND(JHS_PV_IPV*7/RECORDS,2) AS JHS_PV_IPV ,
  ROUND(ZTC_PV_UV*7/RECORDS,2) AS ZTC_PV_UV,
  ROUND(TBK_PV_UV*7/RECORDS,2) AS TBK_PV_UV,
  ROUND(SS_PV_UV*7/RECORDS,2) AS SS_PV_UV,
  ROUND(JHS_PV_UV*7/RECORDS,2) AS JHS_PV_UV,
  ROUND(NUM_AIPAY_HJHS*7/RECORDS,2) AS NUM_AIPAY_HJHS,
  ROUND(AMT_APLIPAY_NJHS*7/RECORDS,2) AS AMT_APLIPAY_NJHS,
  ROUND(QTY_ALIPAY_NJHS*7/RECORDS,2) AS QTY_ALIPAY_NJHS,
  ROUND(UNUM_ALIPAY_NJHS*7/RECORDS,2) AS UNUM_ALIPAY_NJHS
FROM TC_TEMP;



-- -------------------------------------------------------------------------------------
-- FOR SUBMISSION
DROP TABLE TC_TEMP;
CREATE TABLE TC_TEMP AS
SELECT
  ITEM_ID,
  COUNT(*) AS RECORDS,
  SUM(PV_IPV) AS PV_IPV,
  SUM(PV_UV) AS PV_UV ,
  SUM(CART_IPV) AS CART_IPV,
  SUM(CART_UV) AS CART_UV,
  SUM(COLLECT_UV) AS COLLECT_UV,
  SUM(NUM_GMV) AS NUM_GMV,
  SUM(AMT_GMV) AS AMT_GMV,
  SUM(QTY_GMV) AS QTY_GMV,
  SUM(UNUM_GMV) AS UNUM_GMV,
  SUM(AMT_ALIPAY) AS AMT_ALIPAY,
  SUM(NUM_APLIPAY) AS NUM_APLIPAY,
  SUM(QTY_APIPAY) AS QTY_APIPAY,
  SUM(UNUM_ALIPAY) AS UNUM_ALIPAY,
  SUM(ZTC_PV_IPV) AS ZTC_PV_IPV,
  SUM(TBK_PV_IPV) AS TBK_PV_IPV,
  SUM(SS_PV_IPV) AS SS_PV_IPV,
  SUM(JHS_PV_IPV) AS JHS_PV_IPV ,
  SUM(ZTC_PV_UV) AS ZTC_PV_UV,
  SUM(TBK_PV_UV) AS TBK_PV_UV,
  SUM(SS_PV_UV) AS SS_PV_UV,
  SUM(JHS_PV_UV) AS JHS_PV_UV,
  SUM(NUM_AIPAY_HJHS) AS NUM_AIPAY_HJHS,
  SUM(AMT_APLIPAY_NJHS) AS AMT_APLIPAY_NJHS,
  SUM(QTY_ALIPAY_NJHS) AS QTY_ALIPAY_NJHS,
  SUM(UNUM_ALIPAY_NJHS) AS UNUM_ALIPAY_NJHS
FROM TC_CN_SUB_20150929_1227
WHERE TIME >='20151221' AND TIME <='20151227'
GROUP BY ITEM_ID;

DROP TABLE TC_UI_FEATURE_SUB;
CREATE TABLE TC_UI_FEATURE_SUB AS
SELECT 
  ITEM_ID,
  ROUND(PV_IPV*7/RECORDS,2) AS PV_IPV,
  ROUND(PV_UV*7/RECORDS,2) AS PV_UV ,
  ROUND(CART_IPV*7/RECORDS,2) AS CART_IPV,
  ROUND(CART_UV*7/RECORDS,2) AS CART_UV,
  ROUND(COLLECT_UV*7/RECORDS,2) AS COLLECT_UV,
  ROUND(NUM_GMV*7/RECORDS,2) AS NUM_GMV,
  ROUND(AMT_GMV*7/RECORDS,2) AS AMT_GMV,
  ROUND(QTY_GMV*7/RECORDS,2) AS QTY_GMV,
  ROUND(UNUM_GMV*7/RECORDS,2) AS UNUM_GMV,
  ROUND(AMT_ALIPAY*7/RECORDS,2) AS AMT_ALIPAY,
  ROUND(NUM_APLIPAY*7/RECORDS,2) AS NUM_APLIPAY,
  ROUND(QTY_APIPAY*7/RECORDS,2) AS QTY_APIPAY,
  ROUND(UNUM_ALIPAY*7/RECORDS,2) AS UNUM_ALIPAY,
  ROUND(ZTC_PV_IPV*7/RECORDS,2) AS ZTC_PV_IPV,
  ROUND(TBK_PV_IPV*7/RECORDS,2) AS TBK_PV_IPV,
  ROUND(SS_PV_IPV*7/RECORDS,2) AS SS_PV_IPV,
  ROUND(JHS_PV_IPV*7/RECORDS,2) AS JHS_PV_IPV ,
  ROUND(ZTC_PV_UV*7/RECORDS,2) AS ZTC_PV_UV,
  ROUND(TBK_PV_UV*7/RECORDS,2) AS TBK_PV_UV,
  ROUND(SS_PV_UV*7/RECORDS,2) AS SS_PV_UV,
  ROUND(JHS_PV_UV*7/RECORDS,2) AS JHS_PV_UV,
  ROUND(NUM_AIPAY_HJHS*7/RECORDS,2) AS NUM_AIPAY_HJHS,
  ROUND(AMT_APLIPAY_NJHS*7/RECORDS,2) AS AMT_APLIPAY_NJHS,
  ROUND(QTY_ALIPAY_NJHS*7/RECORDS,2) AS QTY_ALIPAY_NJHS,
  ROUND(UNUM_ALIPAY_NJHS*7/RECORDS,2) AS UNUM_ALIPAY_NJHS
FROM TC_TEMP;
-- SELECT * FROM TC_UI_FEATURE_EVAL;



-- -------------------------------------------------------------------------------------
-- FOR VALIDATION
DROP TABLE TC_TEMP;
CREATE TABLE TC_TEMP AS
SELECT
  ITEM_ID,
  COUNT(*) AS RECORDS,
  SUM(PV_IPV) AS PV_IPV,
  SUM(PV_UV) AS PV_UV ,
  SUM(CART_IPV) AS CART_IPV,
  SUM(CART_UV) AS CART_UV,
  SUM(COLLECT_UV) AS COLLECT_UV,
  SUM(NUM_GMV) AS NUM_GMV,
  SUM(AMT_GMV) AS AMT_GMV,
  SUM(QTY_GMV) AS QTY_GMV,
  SUM(UNUM_GMV) AS UNUM_GMV,
  SUM(AMT_ALIPAY) AS AMT_ALIPAY,
  SUM(NUM_APLIPAY) AS NUM_APLIPAY,
  SUM(QTY_APIPAY) AS QTY_APIPAY,
  SUM(UNUM_ALIPAY) AS UNUM_ALIPAY,
  SUM(ZTC_PV_IPV) AS ZTC_PV_IPV,
  SUM(TBK_PV_IPV) AS TBK_PV_IPV,
  SUM(SS_PV_IPV) AS SS_PV_IPV,
  SUM(JHS_PV_IPV) AS JHS_PV_IPV ,
  SUM(ZTC_PV_UV) AS ZTC_PV_UV,
  SUM(TBK_PV_UV) AS TBK_PV_UV,
  SUM(SS_PV_UV) AS SS_PV_UV,
  SUM(JHS_PV_UV) AS JHS_PV_UV,
  SUM(NUM_AIPAY_HJHS) AS NUM_AIPAY_HJHS,
  SUM(AMT_APLIPAY_NJHS) AS AMT_APLIPAY_NJHS,
  SUM(QTY_ALIPAY_NJHS) AS QTY_ALIPAY_NJHS,
  SUM(UNUM_ALIPAY_NJHS) AS UNUM_ALIPAY_NJHS
FROM TC_CN_VALIDATION_20151015_1227
WHERE TIME >='20151207' AND TIME <='20151213'
GROUP BY ITEM_ID;

DROP TABLE TC_UI_FEATURE_VALIDATION;
CREATE TABLE TC_UI_FEATURE_VALIDATION AS
SELECT 
  ITEM_ID,
  ROUND(PV_IPV*7/RECORDS,2) AS PV_IPV,
  ROUND(PV_UV*7/RECORDS,2) AS PV_UV ,
  ROUND(CART_IPV*7/RECORDS,2) AS CART_IPV,
  ROUND(CART_UV*7/RECORDS,2) AS CART_UV,
  ROUND(COLLECT_UV*7/RECORDS,2) AS COLLECT_UV,
  ROUND(NUM_GMV*7/RECORDS,2) AS NUM_GMV,
  ROUND(AMT_GMV*7/RECORDS,2) AS AMT_GMV,
  ROUND(QTY_GMV*7/RECORDS,2) AS QTY_GMV,
  ROUND(UNUM_GMV*7/RECORDS,2) AS UNUM_GMV,
  ROUND(AMT_ALIPAY*7/RECORDS,2) AS AMT_ALIPAY,
  ROUND(NUM_APLIPAY*7/RECORDS,2) AS NUM_APLIPAY,
  ROUND(QTY_APIPAY*7/RECORDS,2) AS QTY_APIPAY,
  ROUND(UNUM_ALIPAY*7/RECORDS,2) AS UNUM_ALIPAY,
  ROUND(ZTC_PV_IPV*7/RECORDS,2) AS ZTC_PV_IPV,
  ROUND(TBK_PV_IPV*7/RECORDS,2) AS TBK_PV_IPV,
  ROUND(SS_PV_IPV*7/RECORDS,2) AS SS_PV_IPV,
  ROUND(JHS_PV_IPV*7/RECORDS,2) AS JHS_PV_IPV ,
  ROUND(ZTC_PV_UV*7/RECORDS,2) AS ZTC_PV_UV,
  ROUND(TBK_PV_UV*7/RECORDS,2) AS TBK_PV_UV,
  ROUND(SS_PV_UV*7/RECORDS,2) AS SS_PV_UV,
  ROUND(JHS_PV_UV*7/RECORDS,2) AS JHS_PV_UV,
  ROUND(NUM_AIPAY_HJHS*7/RECORDS,2) AS NUM_AIPAY_HJHS,
  ROUND(AMT_APLIPAY_NJHS*7/RECORDS,2) AS AMT_APLIPAY_NJHS,
  ROUND(QTY_ALIPAY_NJHS*7/RECORDS,2) AS QTY_ALIPAY_NJHS,
  ROUND(UNUM_ALIPAY_NJHS*7/RECORDS,2) AS UNUM_ALIPAY_NJHS
FROM TC_TEMP;

DROP TABLE TC_TEMP;
-- SELECT * FROM TC_UI_FEATURE_EVAL;


