-- 提取商品类别信息
-- 生成表格TC_ITEM_FEATURE
DROP TABLE TC_ITEM_FEATURE_TRAIN;
CREATE TABLE TC_ITEM_FEATURE_TRAIN AS
SELECT 
  ITEM_ID,
  CATE_ID,
  CATE_LEVEL_ID,
  BRAND_ID,
  SUPPLIER_ID 
FROM TC_CN_TRAIN_20141121_0304
WHERE TIME >= '20141121' AND TIME <= '20150218'
GROUP BY ITEM_ID,CATE_ID,CATE_LEVEL_ID,BRAND_ID,SUPPLIER_ID;


DROP TABLE TC_ITEM_FEATURE_TEST;
CREATE TABLE TC_ITEM_FEATURE_TEST AS
SELECT 
  ITEM_ID,
  CATE_ID,
  CATE_LEVEL_ID,
  BRAND_ID,
  SUPPLIER_ID 
FROM TC_CN_TEST_20150305_0616
WHERE TIME >= '20150305' AND TIME <= '20150602'
GROUP BY ITEM_ID,CATE_ID,CATE_LEVEL_ID,BRAND_ID,SUPPLIER_ID;


-- -------------------------------------------------------------
DROP TABLE TC_ITEM_FEATURE_EVAL;
CREATE TABLE TC_ITEM_FEATURE_EVAL AS
SELECT 
  ITEM_ID,
  CATE_ID,
  CATE_LEVEL_ID,
  BRAND_ID,
  SUPPLIER_ID 
FROM TC_CN_EVAL_20150617_0928
WHERE TIME >= '20150617' AND TIME <= '20150914'
GROUP BY ITEM_ID,CATE_ID,CATE_LEVEL_ID,BRAND_ID,SUPPLIER_ID;


-- -------------------------------------------------------------
DROP TABLE TC_ITEM_FEATURE_SUB;
CREATE TABLE TC_ITEM_FEATURE_SUB AS
SELECT 
  ITEM_ID,
  CATE_ID,
  CATE_LEVEL_ID,
  BRAND_ID,
  SUPPLIER_ID 
FROM TC_CN_SUB_20150929_1227
WHERE TIME >= '20150929' AND TIME <= '20151227'
GROUP BY ITEM_ID,CATE_ID,CATE_LEVEL_ID,BRAND_ID,SUPPLIER_ID;

-- ------------------------------------------------------------
DROP TABLE TC_ITEM_FEATURE_VALIDATION;
CREATE TABLE TC_ITEM_FEATURE_VALIDATION AS
SELECT 
  ITEM_ID,
  CATE_ID,
  CATE_LEVEL_ID,
  BRAND_ID,
  SUPPLIER_ID 
FROM TC_CN_VALIDATION_20151015_1227
WHERE TIME >= '20151015' AND TIME <= '20151213'
GROUP BY ITEM_ID,CATE_ID,CATE_LEVEL_ID,BRAND_ID,SUPPLIER_ID;
