-- 提取商品类别信息
-- 生成表格TC_ITEM_FEATURE
DROP TABLE TC_ITEM_FEATURE_TRAIN_ST;
CREATE TABLE TC_ITEM_FEATURE_TRAIN_ST AS
SELECT 
  ITEM_ID,
  STORE_CODE,
  CATE_ID,
  CATE_LEVEL_ID,
  BRAND_ID,
  SUPPLIER_ID 
FROM TC_CN_TRAIN_20141121_0304_ST
WHERE TIME >= '20141121' AND TIME <= '20150218'
GROUP BY ITEM_ID,STORE_CODE,CATE_ID,CATE_LEVEL_ID,BRAND_ID,SUPPLIER_ID;

DROP TABLE TC_ITEM_FEATURE_TEST_ST;
CREATE TABLE TC_ITEM_FEATURE_TEST_ST AS
SELECT 
  ITEM_ID,
  STORE_CODE,
  CATE_ID,
  CATE_LEVEL_ID,
  BRAND_ID,
  SUPPLIER_ID 
FROM TC_CN_TEST_20150305_0616_ST
WHERE TIME >= '20150305' AND TIME <= '20150602'
GROUP BY ITEM_ID,STORE_CODE,CATE_ID,CATE_LEVEL_ID,BRAND_ID,SUPPLIER_ID;

DROP TABLE TC_ITEM_FEATURE_EVAL_ST;
CREATE TABLE TC_ITEM_FEATURE_EVAL_ST AS
SELECT 
  ITEM_ID,
  STORE_CODE,
  CATE_ID,
  CATE_LEVEL_ID,
  BRAND_ID,
  SUPPLIER_ID 
FROM TC_CN_EVAL_20150617_0928_ST
WHERE TIME >= '20150617' AND TIME <= '20150904'
GROUP BY ITEM_ID,STORE_CODE,CATE_ID,CATE_LEVEL_ID,BRAND_ID,SUPPLIER_ID;


DROP TABLE TC_ITEM_FEATURE_SUB_ST;
CREATE TABLE TC_ITEM_FEATURE_SUB_ST AS
SELECT 
  ITEM_ID,
  STORE_CODE,
  CATE_ID,
  CATE_LEVEL_ID,
  BRAND_ID,
  SUPPLIER_ID 
FROM TC_CN_SUB_20150929_1227_ST
WHERE TIME >= '20150929' AND TIME <= '20151227'
GROUP BY ITEM_ID,STORE_CODE,CATE_ID,CATE_LEVEL_ID,BRAND_ID,SUPPLIER_ID;

-- validation
DROP TABLE TC_ITEM_FEATURE_VALIDAT_ST;
CREATE TABLE TC_ITEM_FEATURE_VALIDAT_ST AS
SELECT 
  ITEM_ID,
  STORE_CODE,
  CATE_ID,
  CATE_LEVEL_ID,
  BRAND_ID,
  SUPPLIER_ID 
FROM TC_CN_VALIDAT_20150929_1227_ST
WHERE TIME >= '20150929' AND TIME <= '20151213'
GROUP BY ITEM_ID,STORE_CODE,CATE_ID,CATE_LEVEL_ID,BRAND_ID,SUPPLIER_ID;

