

-- FOR TRAINING
DROP TABLE TC_CN_TRAIN_DATASET;
CREATE TABLE TC_CN_TRAIN_DATASET AS
SELECT 
  I.ITEM_ID,
  I.CATE_ID,
  I.CATE_LEVEL_ID,
  I.BRAND_ID,
  I.SUPPLIER_ID,
  --UI FEATURE
  UI.PV_IPV,
  UI.PV_UV ,
  UI.CART_IPV,
  UI.CART_UV,
  UI.COLLECT_UV,
  UI.NUM_GMV,
  UI.AMT_GMV,
  UI.QTY_GMV,
  UI.UNUM_GMV,
  UI.AMT_ALIPAY,
  UI.NUM_APLIPAY,
  UI.QTY_APIPAY,
  UI.UNUM_ALIPAY,
  UI.ZTC_PV_IPV,
  UI.TBK_PV_IPV,
  UI.SS_PV_IPV,
  UI.JHS_PV_IPV ,
  UI.ZTC_PV_UV,
  UI.TBK_PV_UV,
  UI.SS_PV_UV,
  UI.JHS_PV_UV,
  UI.NUM_AIPAY_HJHS,
  UI.AMT_APLIPAY_NJHS,
  UI.QTY_ALIPAY_NJHS,
  UI.UNUM_ALIPAY_NJHS,
  --SALES FEATURE
  S.SALES3,
  S.SALES5,
  S.SALES7,
  S.SALES14,
  S.SALES30,
  S.SALES60,
  S.SALES90,
  --LABEL
  L.SALES AS LABEL
FROM TC_ITEM_FEATURE_TRAIN I
LEFT JOIN TC_UI_FEATURE_TRAIN UI ON I.ITEM_ID=UI.ITEM_ID
LEFT JOIN TC_SALES_FEATURE_TRAIN S ON I.ITEM_ID = S.ITEM_ID
LEFT JOIN TC_CN_LABELS_TRAIN L ON I.ITEM_ID =L.ITEM_ID; 


-- 预测前一周没有用户与商品之间的交互记录，设为0
UPDATE TC_CN_TRAIN_DATASET SET  PV_IPV=0 WHERE PV_IPV IS NULL;

UPDATE TC_CN_TRAIN_DATASET SET  PV_UV=0 WHERE PV_UV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  CART_IPV=0 WHERE CART_IPV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  CART_UV=0 WHERE CART_UV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  COLLECT_UV=0 WHERE COLLECT_UV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  NUM_GMV=0 WHERE NUM_GMV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  AMT_GMV=0 WHERE AMT_GMV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  QTY_GMV=0 WHERE QTY_GMV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  UNUM_GMV=0 WHERE UNUM_GMV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  AMT_ALIPAY=0 WHERE AMT_ALIPAY IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  NUM_APLIPAY=0 WHERE NUM_APLIPAY IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  QTY_APIPAY=0 WHERE QTY_APIPAY IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  UNUM_ALIPAY=0 WHERE UNUM_ALIPAY IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  ZTC_PV_IPV=0 WHERE ZTC_PV_IPV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  TBK_PV_IPV=0 WHERE TBK_PV_IPV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  SS_PV_IPV=0 WHERE SS_PV_IPV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  JHS_PV_IPV=0 WHERE JHS_PV_IPV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  ZTC_PV_UV=0 WHERE ZTC_PV_UV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  TBK_PV_UV=0 WHERE TBK_PV_UV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  SS_PV_UV=0 WHERE SS_PV_UV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  JHS_PV_UV=0 WHERE JHS_PV_UV IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  NUM_AIPAY_HJHS=0 WHERE NUM_AIPAY_HJHS IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  AMT_APLIPAY_NJHS=0 WHERE AMT_APLIPAY_NJHS IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  QTY_ALIPAY_NJHS=0 WHERE QTY_ALIPAY_NJHS IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  UNUM_ALIPAY_NJHS=0 WHERE UNUM_ALIPAY_NJHS IS NULL;
UPDATE TC_CN_TRAIN_DATASET SET  LABEL=0 WHERE LABEL IS NULL;



-- --------------------------------------------------------------------------------
-- FOR TESTING
DROP TABLE TC_CN_TEST_DATASET;
CREATE TABLE TC_CN_TEST_DATASET AS
SELECT 
  I.ITEM_ID,
  I.CATE_ID,
  I.CATE_LEVEL_ID,
  I.BRAND_ID,
  I.SUPPLIER_ID,
  --UI FEATURE
  UI.PV_IPV,
  UI.PV_UV ,
  UI.CART_IPV,
  UI.CART_UV,
  UI.COLLECT_UV,
  UI.NUM_GMV,
  UI.AMT_GMV,
  UI.QTY_GMV,
  UI.UNUM_GMV,
  UI.AMT_ALIPAY,
  UI.NUM_APLIPAY,
  UI.QTY_APIPAY,
  UI.UNUM_ALIPAY,
  UI.ZTC_PV_IPV,
  UI.TBK_PV_IPV,
  UI.SS_PV_IPV,
  UI.JHS_PV_IPV ,
  UI.ZTC_PV_UV,
  UI.TBK_PV_UV,
  UI.SS_PV_UV,
  UI.JHS_PV_UV,
  UI.NUM_AIPAY_HJHS,
  UI.AMT_APLIPAY_NJHS,
  UI.QTY_ALIPAY_NJHS,
  UI.UNUM_ALIPAY_NJHS,
  --SALES FEATURE
  S.SALES3,
  S.SALES5,
  S.SALES7,
  S.SALES14,
  S.SALES30,
  S.SALES60,
  S.SALES90,
  --LABEL
  L.SALES AS LABEL
FROM TC_ITEM_FEATURE_TEST I
LEFT JOIN TC_UI_FEATURE_TEST UI ON I.ITEM_ID=UI.ITEM_ID
LEFT JOIN TC_SALES_FEATURE_TEST S ON I.ITEM_ID = S.ITEM_ID
LEFT JOIN TC_CN_LABELS_TEST L ON I.ITEM_ID =L.ITEM_ID; 


-- 预测前一周没有用户与商品之间的交互记录，设为0
UPDATE TC_CN_TEST_DATASET SET  PV_IPV=0 WHERE PV_IPV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  PV_UV=0 WHERE PV_UV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  CART_IPV=0 WHERE CART_IPV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  CART_UV=0 WHERE CART_UV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  COLLECT_UV=0 WHERE COLLECT_UV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  NUM_GMV=0 WHERE NUM_GMV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  AMT_GMV=0 WHERE AMT_GMV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  QTY_GMV=0 WHERE QTY_GMV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  UNUM_GMV=0 WHERE UNUM_GMV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  AMT_ALIPAY=0 WHERE AMT_ALIPAY IS NULL;
UPDATE TC_CN_TEST_DATASET SET  NUM_APLIPAY=0 WHERE NUM_APLIPAY IS NULL;
UPDATE TC_CN_TEST_DATASET SET  QTY_APIPAY=0 WHERE QTY_APIPAY IS NULL;
UPDATE TC_CN_TEST_DATASET SET  UNUM_ALIPAY=0 WHERE UNUM_ALIPAY IS NULL;
UPDATE TC_CN_TEST_DATASET SET  ZTC_PV_IPV=0 WHERE ZTC_PV_IPV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  TBK_PV_IPV=0 WHERE TBK_PV_IPV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  SS_PV_IPV=0 WHERE SS_PV_IPV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  JHS_PV_IPV=0 WHERE JHS_PV_IPV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  ZTC_PV_UV=0 WHERE ZTC_PV_UV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  TBK_PV_UV=0 WHERE TBK_PV_UV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  SS_PV_UV=0 WHERE SS_PV_UV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  JHS_PV_UV=0 WHERE JHS_PV_UV IS NULL;
UPDATE TC_CN_TEST_DATASET SET  NUM_AIPAY_HJHS=0 WHERE NUM_AIPAY_HJHS IS NULL;
UPDATE TC_CN_TEST_DATASET SET  AMT_APLIPAY_NJHS=0 WHERE AMT_APLIPAY_NJHS IS NULL;
UPDATE TC_CN_TEST_DATASET SET  QTY_ALIPAY_NJHS=0 WHERE QTY_ALIPAY_NJHS IS NULL;
UPDATE TC_CN_TEST_DATASET SET  UNUM_ALIPAY_NJHS=0 WHERE UNUM_ALIPAY_NJHS IS NULL;
UPDATE TC_CN_TEST_DATASET SET  LABEL=0 WHERE LABEL IS NULL;


-- ---------------------------------------------------------------------------------
-- FOR EVALATING DATA
DROP TABLE TC_CN_EVAL_DATASET;
CREATE TABLE TC_CN_EVAL_DATASET AS
SELECT 
  T.ITEM_ID,
  T.CATE_ID,
  T.CATE_LEVEL_ID,
  T.BRAND_ID,
  T.SUPPLIER_ID,
  --UI FEATURE
  UI.PV_IPV,
  UI.PV_UV ,
  UI.CART_IPV,
  UI.CART_UV,
  UI.COLLECT_UV,
  UI.NUM_GMV,
  UI.AMT_GMV,
  UI.QTY_GMV,
  UI.UNUM_GMV,
  UI.AMT_ALIPAY,
  UI.NUM_APLIPAY,
  UI.QTY_APIPAY,
  UI.UNUM_ALIPAY,
  UI.ZTC_PV_IPV,
  UI.TBK_PV_IPV,
  UI.SS_PV_IPV,
  UI.JHS_PV_IPV ,
  UI.ZTC_PV_UV,
  UI.TBK_PV_UV,
  UI.SS_PV_UV,
  UI.JHS_PV_UV,
  UI.NUM_AIPAY_HJHS,
  UI.AMT_APLIPAY_NJHS,
  UI.QTY_ALIPAY_NJHS,
  UI.UNUM_ALIPAY_NJHS,
  --SALES FEATURE
  S.SALES3,
  S.SALES5,
  S.SALES7,
  S.SALES14,
  S.SALES30,
  S.SALES60,
  S.SALES90,
  --LABEL
  L.SALES AS LABEL
FROM TC_ITEM_FEATURE_EVAL T
LEFT JOIN TC_UI_FEATURE_EVAL UI ON T.ITEM_ID=UI.ITEM_ID
LEFT JOIN TC_SALES_FEATURE_EVAL S ON T.ITEM_ID = S.ITEM_ID
LEFT JOIN TC_CN_LABELS_EVAL L ON T.ITEM_ID =L.ITEM_ID;


-- 预测前一周没有用户与商品之间的交互记录，设为0
UPDATE TC_CN_EVAL_DATASET SET  PV_IPV=0 WHERE PV_IPV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  PV_UV=0 WHERE PV_UV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  CART_IPV=0 WHERE CART_IPV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  CART_UV=0 WHERE CART_UV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  COLLECT_UV=0 WHERE COLLECT_UV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  NUM_GMV=0 WHERE NUM_GMV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  AMT_GMV=0 WHERE AMT_GMV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  QTY_GMV=0 WHERE QTY_GMV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  UNUM_GMV=0 WHERE UNUM_GMV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  AMT_ALIPAY=0 WHERE AMT_ALIPAY IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  NUM_APLIPAY=0 WHERE NUM_APLIPAY IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  QTY_APIPAY=0 WHERE QTY_APIPAY IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  UNUM_ALIPAY=0 WHERE UNUM_ALIPAY IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  ZTC_PV_IPV=0 WHERE ZTC_PV_IPV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  TBK_PV_IPV=0 WHERE TBK_PV_IPV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  SS_PV_IPV=0 WHERE SS_PV_IPV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  JHS_PV_IPV=0 WHERE JHS_PV_IPV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  ZTC_PV_UV=0 WHERE ZTC_PV_UV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  TBK_PV_UV=0 WHERE TBK_PV_UV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  SS_PV_UV=0 WHERE SS_PV_UV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  JHS_PV_UV=0 WHERE JHS_PV_UV IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  NUM_AIPAY_HJHS=0 WHERE NUM_AIPAY_HJHS IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  AMT_APLIPAY_NJHS=0 WHERE AMT_APLIPAY_NJHS IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  QTY_ALIPAY_NJHS=0 WHERE QTY_ALIPAY_NJHS IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  UNUM_ALIPAY_NJHS=0 WHERE UNUM_ALIPAY_NJHS IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  LABEL=0 WHERE LABEL IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  SALES3=0 WHERE SALES3 IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  SALES5=0 WHERE SALES5 IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  SALES7=0 WHERE SALES7 IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  SALES14=0 WHERE SALES14 IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  SALES30=0 WHERE SALES30 IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  SALES60=0 WHERE SALES60 IS NULL;
UPDATE TC_CN_EVAL_DATASET SET  SALES90=0 WHERE SALES90 IS NULL;

-- ---------------------------------------------------------------------------------
-- FOR VALIDATION DATA
DROP TABLE TC_CN_VALIDATION_DATASET;
CREATE TABLE TC_CN_VALIDATION_DATASET AS
SELECT 
  T.ITEM_ID,
  T.CATE_ID,
  T.CATE_LEVEL_ID,
  T.BRAND_ID,
  T.SUPPLIER_ID,
  --UI FEATURE
  UI.PV_IPV,
  UI.PV_UV ,
  UI.CART_IPV,
  UI.CART_UV,
  UI.COLLECT_UV,
  UI.NUM_GMV,
  UI.AMT_GMV,
  UI.QTY_GMV,
  UI.UNUM_GMV,
  UI.AMT_ALIPAY,
  UI.NUM_APLIPAY,
  UI.QTY_APIPAY,
  UI.UNUM_ALIPAY,
  UI.ZTC_PV_IPV,
  UI.TBK_PV_IPV,
  UI.SS_PV_IPV,
  UI.JHS_PV_IPV ,
  UI.ZTC_PV_UV,
  UI.TBK_PV_UV,
  UI.SS_PV_UV,
  UI.JHS_PV_UV,
  UI.NUM_AIPAY_HJHS,
  UI.AMT_APLIPAY_NJHS,
  UI.QTY_ALIPAY_NJHS,
  UI.UNUM_ALIPAY_NJHS,
  --SALES FEATURE
  S.SALES3,
  S.SALES5,
  S.SALES7,
  S.SALES14,
  S.SALES30,
  S.SALES60,
  S.SALES90,
  --LABEL
  L.SALES AS LABEL
FROM TC_ITEM_FEATURE_VALIDATION T
LEFT JOIN TC_UI_FEATURE_VALIDATION UI ON T.ITEM_ID=UI.ITEM_ID
LEFT JOIN TC_SALES_FEATURE_VALIDATION S ON T.ITEM_ID = S.ITEM_ID
LEFT JOIN TC_CN_LABELS_VALIDATION L ON T.ITEM_ID =L.ITEM_ID;


-- 预测前一周没有用户与商品之间的交互记录，设为0
UPDATE TC_CN_VALIDATION_DATASET SET  PV_IPV=0 WHERE PV_IPV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  PV_UV=0 WHERE PV_UV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  CART_IPV=0 WHERE CART_IPV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  CART_UV=0 WHERE CART_UV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  COLLECT_UV=0 WHERE COLLECT_UV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  NUM_GMV=0 WHERE NUM_GMV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  AMT_GMV=0 WHERE AMT_GMV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  QTY_GMV=0 WHERE QTY_GMV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  UNUM_GMV=0 WHERE UNUM_GMV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  AMT_ALIPAY=0 WHERE AMT_ALIPAY IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  NUM_APLIPAY=0 WHERE NUM_APLIPAY IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  QTY_APIPAY=0 WHERE QTY_APIPAY IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  UNUM_ALIPAY=0 WHERE UNUM_ALIPAY IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  ZTC_PV_IPV=0 WHERE ZTC_PV_IPV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  TBK_PV_IPV=0 WHERE TBK_PV_IPV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  SS_PV_IPV=0 WHERE SS_PV_IPV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  JHS_PV_IPV=0 WHERE JHS_PV_IPV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  ZTC_PV_UV=0 WHERE ZTC_PV_UV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  TBK_PV_UV=0 WHERE TBK_PV_UV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  SS_PV_UV=0 WHERE SS_PV_UV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  JHS_PV_UV=0 WHERE JHS_PV_UV IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  NUM_AIPAY_HJHS=0 WHERE NUM_AIPAY_HJHS IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  AMT_APLIPAY_NJHS=0 WHERE AMT_APLIPAY_NJHS IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  QTY_ALIPAY_NJHS=0 WHERE QTY_ALIPAY_NJHS IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  UNUM_ALIPAY_NJHS=0 WHERE UNUM_ALIPAY_NJHS IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  LABEL=0 WHERE LABEL IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  SALES3=0 WHERE SALES3 IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  SALES5=0 WHERE SALES5 IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  SALES7=0 WHERE SALES7 IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  SALES14=0 WHERE SALES14 IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  SALES30=0 WHERE SALES30 IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  SALES60=0 WHERE SALES60 IS NULL;
UPDATE TC_CN_VALIDATION_DATASET SET  SALES90=0 WHERE SALES90 IS NULL;


-- ---------------------------------------------------------------------------------
-- FOR SUBMISSION DATA
DROP TABLE TC_CN_SUB_DATASET;
CREATE TABLE TC_CN_SUB_DATASET AS
SELECT 
  I.ITEM_ID,
  I.CATE_ID,
  I.CATE_LEVEL_ID,
  I.BRAND_ID,
  I.SUPPLIER_ID,
  --UI FEATURE
  UI.PV_IPV,
  UI.PV_UV ,
  UI.CART_IPV,
  UI.CART_UV,
  UI.COLLECT_UV,
  UI.NUM_GMV,
  UI.AMT_GMV,
  UI.QTY_GMV,
  UI.UNUM_GMV,
  UI.AMT_ALIPAY,
  UI.NUM_APLIPAY,
  UI.QTY_APIPAY,
  UI.UNUM_ALIPAY,
  UI.ZTC_PV_IPV,
  UI.TBK_PV_IPV,
  UI.SS_PV_IPV,
  UI.JHS_PV_IPV ,
  UI.ZTC_PV_UV,
  UI.TBK_PV_UV,
  UI.SS_PV_UV,
  UI.JHS_PV_UV,
  UI.NUM_AIPAY_HJHS,
  UI.AMT_APLIPAY_NJHS,
  UI.QTY_ALIPAY_NJHS,
  UI.UNUM_ALIPAY_NJHS,
  --SALES FEATURE
  S.SALES3,
  S.SALES5,
  S.SALES7,
  S.SALES14,
  S.SALES30,
  S.SALES60,
  S.SALES90

FROM TC_ITEM_FEATURE_SUB I
LEFT JOIN TC_UI_FEATURE_SUB UI ON I.ITEM_ID=UI.ITEM_ID
LEFT JOIN TC_SALES_FEATURE_SUB S ON I.ITEM_ID = S.ITEM_ID;


-- 预测前一周没有用户与商品之间的交互记录，设为0
UPDATE TC_CN_SUB_DATASET SET  PV_IPV=0 WHERE PV_IPV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  PV_UV=0 WHERE PV_UV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  CART_IPV=0 WHERE CART_IPV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  CART_UV=0 WHERE CART_UV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  COLLECT_UV=0 WHERE COLLECT_UV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  NUM_GMV=0 WHERE NUM_GMV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  AMT_GMV=0 WHERE AMT_GMV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  QTY_GMV=0 WHERE QTY_GMV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  UNUM_GMV=0 WHERE UNUM_GMV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  AMT_ALIPAY=0 WHERE AMT_ALIPAY IS NULL;
UPDATE TC_CN_SUB_DATASET SET  NUM_APLIPAY=0 WHERE NUM_APLIPAY IS NULL;
UPDATE TC_CN_SUB_DATASET SET  QTY_APIPAY=0 WHERE QTY_APIPAY IS NULL;
UPDATE TC_CN_SUB_DATASET SET  UNUM_ALIPAY=0 WHERE UNUM_ALIPAY IS NULL;
UPDATE TC_CN_SUB_DATASET SET  ZTC_PV_IPV=0 WHERE ZTC_PV_IPV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  TBK_PV_IPV=0 WHERE TBK_PV_IPV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  SS_PV_IPV=0 WHERE SS_PV_IPV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  JHS_PV_IPV=0 WHERE JHS_PV_IPV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  ZTC_PV_UV=0 WHERE ZTC_PV_UV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  TBK_PV_UV=0 WHERE TBK_PV_UV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  SS_PV_UV=0 WHERE SS_PV_UV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  JHS_PV_UV=0 WHERE JHS_PV_UV IS NULL;
UPDATE TC_CN_SUB_DATASET SET  NUM_AIPAY_HJHS=0 WHERE NUM_AIPAY_HJHS IS NULL;
UPDATE TC_CN_SUB_DATASET SET  AMT_APLIPAY_NJHS=0 WHERE AMT_APLIPAY_NJHS IS NULL;
UPDATE TC_CN_SUB_DATASET SET  QTY_ALIPAY_NJHS=0 WHERE QTY_ALIPAY_NJHS IS NULL;
UPDATE TC_CN_SUB_DATASET SET  UNUM_ALIPAY_NJHS=0 WHERE UNUM_ALIPAY_NJHS IS NULL;
UPDATE TC_CN_SUB_DATASET SET  SALES3=0 WHERE SALES3 IS NULL;
UPDATE TC_CN_SUB_DATASET SET  SALES5=0 WHERE SALES5 IS NULL;
UPDATE TC_CN_SUB_DATASET SET  SALES7=0 WHERE SALES7 IS NULL;
UPDATE TC_CN_SUB_DATASET SET  SALES14=0 WHERE SALES14 IS NULL;
UPDATE TC_CN_SUB_DATASET SET  SALES30=0 WHERE SALES30 IS NULL;
UPDATE TC_CN_SUB_DATASET SET  SALES60=0 WHERE SALES60 IS NULL;
UPDATE TC_CN_SUB_DATASET SET  SALES90=0 WHERE SALES90 IS NULL;

